### ISSUE TITLE
[Amélioration interaction RDV-S] Mettre à jour le statut du RDV dans RDV-Insertion

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1024]
**Problème**
Lorsqu'un RDV est passé, il faut mettre à jour son statut (honoré, absence excusée etc..).
Cela est fait aujourd'hui dans RDV-Solidarités. Cependant, cela demande de changer de page, et il serait plus simple de le remplir dans RDV-Insertion.

**Solution**
Une fois le RDV passé, il est possible de modifier le statut du RDV dans la page Index et dans la page Show.

Dans la page index:
![image](https://user-images.githubusercontent.com/77394947/235925779-0d3e5dcf-1b17-4ec9-893c-8881b15a6dde.png)

Lorsqu'on passe sur "Statut du RDV à préciser", on peut cliquer et la modale (comme sur RDV-Solidarités) s'ouvre et on peut choisir le statut
![image](https://user-images.githubusercontent.com/77394947/235926180-f197406e-3a1d-474a-827e-812a3bf0d312.png)

Dans la page Show:
![image](https://user-images.githubusercontent.com/77394947/235926269-9638e48a-f66e-487c-bea0-67f64ca94d5b.png)
Idem, il est possible de cliquer sur "Non déterminé" et nous pouvons choisir le statut

**Comment by ClaireCasu** [comment]
Oui en effet, je pense qu'il faut avoir en but d'avoir toujours la même information des deux côtés.

**Comment by Michaelvilleneuve** [comment]
Pour info ça impliquera de mettre en place un système de webhook côté RDVs également, ça me semble une décision assez grosse et dont il faudrait je pense discuter avec eux (cc @aminedhobb qu'en penses-tu ?)

**Comment by Holist** [comment]
Pour info les changements de status dans les rdvs et les participations ont des conséquences en terme de notifications, événements... (et ne réagissent pas de la même manière quand c'est un rdv ou quand c'est une participation qui est annulée par exemple)
Si on passe par l'api (à valider avec rdvs) il faudra garder la même logique. (et sans doute refactoriser certaines choses)
Est ce que ce ne serait pas l'occasion de tester un iframe ? (je lance ca, je n'ai pas réfléchi aux limitations, avantages, inconvénients...)

**Comment by Michaelvilleneuve** [comment]
J'y ai pensé aussi pour l'iframe oui. Je vais t'envoyer la PR finalement l'ajout de l'API était plutôt simple côté RDVs mais à discuter avec vous si vous pensez qu'il y a mieux à faire en effet 👍

**Comment by Michaelvilleneuve** [comment]
@Holist Si tu veux jeter un oeil pour l'instant ça devrait ressembler à ça 
côté RDVI (encore quelques bugs à corriger + tests à faire) : https://github.com/betagouv/rdv-insertion/pull/1347
