### ISSUE TITLE
[Bug] Upserting two participations at the same time

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#1036]
Il y a une erreur sur sentry quand une participation essaie d'être créée alors qu'elle l'a déjà été : https://sentry.incubateur.net/organizations/betagouv/issues/7862/?project=16&query=is%3Aunresolved

Même s'il y a un lock au niveau du `ProcessRdvJob`, un `UpsertRecordJob` doit être enqueued alors que le précédent n'a pas encore été consommé (et donc les participations pas encore créées). 

Peut-être qu'on devrait faire l'upsert de manière synchrone sur ce job particulier qui gère les rdvs **et** les participations.

**Comment by Holist** [comment]
Ce serait pas lié à ça : https://github.com/betagouv/rdv-insertion/issues/1006 ?

**Comment by aminedhobb** [comment]
C'est encore un problème de race condition à la différence qu'ici je pense que ça vient du faire que l'upsert se fait de manière asynchrone (ce qui n'est pas le cas dans les autres jobs)

**Comment by qblanc** [comment]
Pour que l'issue soit bien documentée : le lien sentry renvoie vers des erreurs de l`UpsertRecord` mais liées à de l'upsert d'agents et non de rdv/participations. Elle a visiblement été résolue puisqu'il n'y a plus de cas récent.
En revanche l'erreur décrite survient toujours [ici](https://mattermost.incubateur.net/betagouv/pl/q7rcnxkcejypdedfroucss3rye)
