### ISSUE TITLE
Faire la spec de l'API pour Marseille

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#105]
Faire un doc en utilisant un swagger avec ce que prendra l'endpoint en entrée et ce qu'il donnera en sortie.
Etudier la possibilité de stocker les lieux (avec leur id custom) et rediriger directement la personne vers le lieu dans lien d'invitation.

**Comment by ClaireCasu** [comment]
Date due : semaine du 15 novembre
