### ISSUE TITLE
[Contexte] Nouveau contexte Atelier Collectif pour les assos

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1160]
Nom du contexte
Atelier Co Asso

Paramètres
RDV obligatoire : non
RDV sanctionnable : non
Délai expiration lien : 10 jours
Fichier d'entrée : en mettre un par défaut (ex: Parcours RSA de la Drôme en démo)

Texte type (mail / sms / courrier)

Bonjour [Prénom Nom]

Vous êtes inscrit.e au sein de notre association et à ce titre, vous êtes invité.e à participer à un atelier collectif afin de vous aider dans votre parcours d'insertion.

Pour vous inscrire, vous pouvez accéder au service RDV-Solidarités en cliquant sur le bouton suivant dans les 3 jours:

[M'inscrire]

En cas de problème, contactez le [num organisation]

[signature]

**Comment by aminedhobb** [comment]
On ne configure pas de rappel pour cette catégorie où la participation a l'air optionnel n'est-ce pas ?

**Comment by SalmaBennani** [comment]
si, je veux bien un rappel sur ça aussi stp 🙏

**Comment by SalmaBennani** [comment]
remplacer par cette issue : https://github.com/betagouv/rdv-insertion/issues/1311
