### ISSUE TITLE
[Contexte] Nouveau contexte RDV suivi pour les assos

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1161]
Nom du contexte
Suivi - asso

Paramètres
RDV obligatoire : non
RDV sanctionnable : non
Délai expiration lien : 10 jours
Fichier d'entrée : en mettre un par défaut (ex: Parcours RSA de la Drôme en démo)

Texte type (mail / sms / courrier)

Bonjour [Prénom Nom]

Vous êtes suivi dans une structure d’insertion et à ce titre vous êtes invité.e à participer à un rendez-vous de suivi afin de vous aider dans votre parcours d'insertion.

Pour vous inscrire, vous pouvez accéder au service RDV-Solidarités en cliquant sur le bouton suivant dans les 3 jours:

[M'inscrire]

En cas de problème, contactez le [num organisation]

[Signature]

**Comment by aminedhobb** [comment]
J'ai créé la catégorie correspondante sur RDVS et RDVI.
À la place de "suivi dans une structure d'insertion" j'ai mis "encadré dans une structure d'insertion", parce que la variable doit être placé comme ça au sein des messages de rappel: "En tant que XXX, ...".
J'ai mis "[SUIVI INSERTION]" comme sujet qui apparaîtra dans l'objet des mails.
