### ISSUE TITLE
[Affichage] Changer Rdv-Insertion en rdv-insertion dans l'affichage de l'onglet

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1164]
Aujourd'hui c'est : 
![image](https://github.com/betagouv/rdv-insertion/assets/77394947/d82a2290-8bd9-4b89-861b-b286865ff409)

Il faudrait enlever les majuscules

**Comment by Michaelvilleneuve** [comment]
Corrigé par https://github.com/betagouv/rdv-insertion/pull/1190
