### ISSUE TITLE
[Bug 84] Vérifier que le bug du courrier 64 est du à une manipulation humaine 

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1167]
Sur le 84, on a reçu le message suivant : 
[Mail 84.pdf](https://github.com/betagouv/rdv-insertion/files/12026143/Mail.84.pdf)

Je me demande : 
Si la fiche usager qui a été inscrite sur le [rendez-vous collectif](https://www.rdv-solidarites.fr/admin/organisations/3841/rdvs/1852767) a été créée par nous ou par le CD ou par l'usager : 
![image](https://github.com/betagouv/rdv-insertion/assets/77394947/7d301887-db61-48a9-a1f7-b59d1be98300)

Je pense qu'il faut vérifier car potentiellement c'est un cas de prise de rendez-vous par courrier

**Comment by aminedhobb** [comment]
En fait la personne a été invitée à prendre rdv via rdvi. Une fois sur rdvs la personne s'est loggée avec france connect.
Ensuite c'est l'agent qui a placé sur le rdv en question l'usager france connect (et non pas l'usager créé via rdvi). 
J'ai fusionné les 2 fiches sur RDVS, et j'ai lié la fiche RDVI à la bonne fiche. 
Le rdv remonte maintenant sur rdvi.
