### ISSUE TITLE
[Contextes] Renommer 2 contextes existants et leur configurer des messages de rappel

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1184]
Il faudra renommer les contextes suivants : 
- rsa_atelier_comeptences par atelier_compétences
- rsa_atelier_rencontres_pro par atelier_rencontres_pro

Ces contextes ne semblent pas avoir de rappel, il faudra en créer un sous le même fonctionnement que les invitations avec des variables.

Possibilité de se référer à ce doc : https://docs.google.com/spreadsheets/d/1hwdsu1AhUtRj9r9LHKSWIgr2mogQkE3Kr70tGGFw96E/edit?usp=sharing

**Comment by aminedhobb** [comment]
* rsa_atelier_competences 

Il est utilisé par `Alter Egal` et `ALI Romainville`.  
On veut configurer un message de rappel pour les 2 ? 
Dans quels buts veut-on changer de nom de la catégorie (qui n'est pas visible par les bénéficiaires) ?

* rsa_atelier_rencontres_pro

Utilisé par `Alter Egal` seulement. Mêmes questions.

**Comment by SalmaBennani** [comment]
C'est pour qu'il soit plus générique pour l'utilisateur (SIAE ou Assos) et que ça sorte du RSA.

C'ets bien d'avoir tjrs des rappels sur les invitations, c'est très demandé par nos utilistaurs

**Comment by aminedhobb** [comment]
> C'est bien d'avoir tjrs des rappels sur les invitations, c'est très demandé par nos utilisateurs

Ok mais sur les ateliers c'est des inscriptions libres, on avait dit que ça n'avait pas trop de sens d'avoir des rappels. À la place on voulait envoyer des invitations périodiques (voir #1227) cc @rprebot .
Mais si on veut vraiment des rappels c'est possible pour ces 2 catégories (ça demande juste de rajouter un dev pour avoir un message de rappel pour les ateliers)

**Comment by SalmaBennani** [comment]
oui c'ets vrai qu'avec le périodique, y a plus de besoin tu as raison. Du coup je veux bien juste le changement de nom. Merci

**Comment by aminedhobb** [comment]
@SalmaBennani j'ai changé les noms de ces catégories. 
Juste pour être sûr qu'on soit clair le fait de changer le nom change juste le nom pour les agents sur RDVI et RDVS, les contenus des messages envoyés aux bénéficiaires ne changent pas eux.
