### ISSUE TITLE
[Contextes] Supprimer le contexte 'rsa_insertion_offer'

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1185]
Après avoir vérifié qu'il n'est pas utilisé, il faudrait supprimer le contexte 'rsa_insertion_offer'

**Comment by aminedhobb** [comment]
On a quand même des rdvs qui ont été effectués sur cette catégorie : https://www.rdv-insertion.fr/organisations/27/applicants?motif_category_id=5&status=rdv_seen

Est-ce qu'on veut vraiment la supprimer ? 
Déjà si le PIE Pantin ne veut plus l'afficher il suffit de supprimer la configuration pour cette catégorie depuis l'interface admin de l'orga

**Comment by SalmaBennani** [comment]
@aminedhobb tu peux laisser en effet. On pensait que ce n'était pas utilisé.

Je close ce ticket
