### ISSUE TITLE
[Forcer Adresse] Frocer un lieu qui ne sort pas sur rdv-s

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1274]
Est-il possible de mettre cette adresse : 1 Place 1er Mai, 81100 Castres sur ce lieu https://www.rdv-solidarites.fr/admin/organisations/3905/lieux/23687/edit

Merci

**Comment by Michaelvilleneuve** [comment]
C'est fait 👍 
<img width="676" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/78871bd8-072f-469d-ae61-b7a956239907">
