### ISSUE TITLE
[Paramétrage CD 38] Activer la prescription pour l'organisation Ulisse 38

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1288]

**Comment by aminedhobb** [comment]
@Holist pour activer la prescription il faut bien ajouter le numéro du département ici ? https://github.com/betagouv/rdv-solidarites.fr/blob/086e6a00e158b149d4821df08d8a4df31193679e/app/presenters/admin/prescripteur_experiment_motif_presenter.rb#L29

Si oui, est-ce que je peux te laisser le faire (et te laisser t'assigner l'issue) ?

**Comment by Holist** [comment]
Ce n'est pas nécéssaire du coup. 
Cela sert uniquement à ajouter dans l'interface de façon explicite le terme "et aux prescripteurs" et donner la possibilité d'ouvrir le motif uniquement aux prescripteurs (est ce qu'on en a besoin ?). 
**A partir du moment ou le motif est ouvert aux usagers avec invitation, il est aussi ouvert aux prescripteurs**.
@Evajuliab penses tu que c'est ok de fonctionner comme ça ou il faut faire apparaitre la notion de prescription pour que ce soit plus clair pour les agents. Alors dans ce cas cela s'active par territoire effectivement et ce n'est pas idéal.
Le plus simple et rapide : on peut activer l'option pour toutes les orgas rdv-insertion. Mais dans ce cas est ce que cela ne risque pas de perturber ceux qui n'utilisent pas la prescription ?

![Capture d’écran 2023-09-28 à 11 16 19](https://github.com/betagouv/rdv-insertion/assets/28594222/31c645a7-f67b-4aeb-bc0b-1ed00f0c1b66)
![Capture d’écran 2023-09-28 à 11 16 08](https://github.com/betagouv/rdv-insertion/assets/28594222/9a3c8271-7de5-4beb-ad84-bbfe9534fe94)
