### ISSUE TITLE
[Page rdv-insertion] Mettre à jour la landing page rdv-insertion (wording, public cible, nouvelles fonctionnalités etc)

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1290]
**Bandeau haut** 
- enlever le lien " Communauté de l'inclusion" et le remplacer par "Statistiques d'utilisation"

**Corps de la page**
- Modifier "Accélérez les rendez‑vous RSA et diminuez le taux d'absentéisme" --> "Accélérez les rendez‑vous d'insertion et diminuez le taux d'absentéisme"
- Modifier "RDV-Insertion permet aux départements de gérer facilement l'entrée des bénéficiaires en parcours d'insertion" -->" rdv-insertion permet aux départements et aux structures d'insertion d'organiser facilement leur rendez-vous (individuels, collectifs, entretiens d'embauche, suivi RSA,...)" 
- Dans les 4 images 
     -  modifier "Invitez les bénéficiaires par SMS et email en quelques clics" ---> "Invitez par SMS et email en quelques clics"
     -  modifier "Les bénéficiaires sont responsabilisés et autonomes dans leur prise de rendez-vous" ---> "Les personnes invitées sont autonomes dans leur prise de rendez-vous et bénéficient d'un rappel automatique."
- Rajouter la petite vidéo de démo qui est présente [ici slide 12](https://docs.google.com/presentation/d/15eVrNMaBzxe4BLdLEZWid9dopS4QhTHyLCuuyDoqmyk/edit#slide=id.g22bf03cee36_0_358) : soit à mettre plus bas, soit à mettre à la place de l'image

**Bandeau bleu sponsor**:
Remplacer le texte par "Ce service est proposé par le Groupement d’Intérêt Public "[Plateforme de l’inclusion](https://inclusion.beta.gouv.fr/nos-services/)", créé par arrêté en avril 2022. Sa mission est de développer de nouveaux services publics pour faciliter la vie des personnes en insertion et de celles et ceux qui les accompagnent."

**Bandeau "Ca vous intéresse"?**
Partager l'espace en deux verticale:
- Vous êtes un conseil départemental et souhaitez diminuer le délai d'orientation des bénéficiaires du RSA dans votre département et réduire le taux d'absentéisme du rendez-vous d'orientation ?

Nous sommes à votre écoute pour adapter notre service à vos besoins et vous aider à le déployer pour votre territoire.
Demander une démo : calendly habituel de Claire

- Vous êtes une structure d'insertion (SIAE, associations ou autre) et souhaitez utiliser rdv-insertion pour mieux gérer vos agendas et maximiser le taux de présence à vos rendez-vous?

Nous sommes à votre écoute pour adapter notre service à vos besoins et vous aider à le déployer pour votre territoire.
Demander une démo : Tally d'@Eva, pour qu'elles remplissent le questionnaire en amont

**Bandeau bas**
- Ressources: enlever le lien "Lecteur flux Cnaf"
- Partenaires : enlever Cnaf, Pole emploi et MSA et remplacer par [Plateforme de l'inclusion](https://inclusion.beta.gouv.fr/qui-sommes-nous/)
- Rajouter le logo "Plateforme de l'inclusion" à côté du logo de la République Française, comme sur [cette page](https://inclusion.beta.gouv.fr/)

**Comment by ClaireCasu** [comment]
Quentin : je n'arrive pas à récupérer la vidéo depuis la slide pour [ce ticket](https://github.com/betagouv/rdv-insertion/issues/1290)

Est-ce que tu as la vidéo @SalmaBennani ? Merci!

**Comment by SalmaBennani** [comment]
Yes, elle est là

https://github.com/betagouv/rdv-insertion/assets/118368758/49ee911c-d100-4055-ba1f-e76056db243b
