### ISSUE TITLE
[3]Retravailler le SMS d'invitation

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#13]
Il faut changer le "chargé d'orientation" en "référent" dans le sms (voir mail de Fabienne à ce sujet).

**Comment by qblanc** [comment]
Également : raccourcir l’URL du lien d’invitation

**Comment by ClaireCasu** [comment]
Et raccourcir le texte: 
Le département 26 (Drôme) vous invite à prendre RDV à l'adresse suivante : _url raccourcie_.
Pour tout problème ou difficultés pour prendre RDV, veuillez contacter ...

**Comment by ClaireCasu** [comment]
Je viens de voir dans le sms que j'ai reçu aujourd'hui qu'il manque les "^" (dans êtes et Drôme)

**Comment by aminedhobb** [comment]
Pour l'url d'invitation il faudrait: 

- Créer une nouvelle route `GET /invitations/redirect`
- Cette route prendra en paramètres le token d'invitation (`rdv-insertion.fr/invitations/redirect?token=124213`)
- Au sein de l'action du controller associée (`invitations#redirect`), il faut retrouver le record d'invitation associé au token (404 sinon)
- Faire une migration pour ajouter une colonne `seen` de type booléen sur la table `invitations` qui est égale à `false` par défaut et qu'on update à `true` une fois que le record d'invitation est retrouvé au sein de l'action `invitations#redirect`
- Rediriger l'utilisateur sur le `link` associé à l'invitation qui redirige vers rdv-solidarités

**Comment by aminedhobb** [comment]
Fait ici: #47
