### ISSUE TITLE
[Nouvelle catégorie] Nouveau contexte Atelier Collectif pour les assos

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1311]
## À renseigner

- Nom: Atelier Collectif pour les assos

- Avec rappel ?  OUI /  NON

### Contenu du message

- Mentionner que le rdv est obligatoire ? OUI

- Mentionner une sanction en cas d'absence ? NON

- Choisissez l'un des modèles suivants et remplissez les textes contenant la mention "A REMPLIR". 
Les numéros à côtés de ces variables servent à montrer quand la même variable est réutilisée dans le message de rappel où l'objet de l'email.
Les points de suspensions correspondent aux éventuelles mentions d'obligation ou de sanction.

#### STANDARD 
``` 
Madame XX,
Vous êtes **inscrit.e au sein de notre association** et vous êtes invité à participer à un **atelier collectif**. Pour choisir la date et l'horaire du RDV, 
cliquez sur le lien suivant dans les 3 jours:
www.rdv-insertion.fr/invitations/redirect?uuid=1234
** PHRASE CUSTOM A INSERER DANS MAILS ET COURRIERS SI NECESSAIRE  **
En cas de problème technique, contactez le 01 01 01 01 01.
``` 

** Rappel ** 

```
Madame XX,
En tant que **inscrit.e au sein de notre association**, vous avez reçu un message il y a 3 jours vous invitant à prendre RDV au créneau de votre choix afin de **vous aider dans votre parcours d'insertion**.
Le lien de prise de RDV suivant expire dans X jours: 
www.rdv-insertion.fr/invitations/redirect?uuid=1234
** PHRASE CUSTOM A INSERER DANS MAILS ET COURRIERS SI NECESSAIRE  **
En cas de problème technique, contactez le 01 01 01 01 01.
```

** Objet du mail d'invitation **  

```
[**Parcours d'insertion**]: Votre **atelier collectif** dans le cadre de votre **Parcours d'insertion**
```

**Comment by aminedhobb** [comment]
C'est bon la catégorie est disponible sur RDVI et RDVS (en prod) 🙏
