### ISSUE TITLE
[Paramétrage CD 27] Ajouter une adresse en base pour l'orga Bernay

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1354]
Dans l'orga Bernay, Pour le lieu maison du département : https://www.rdv-solidarites.fr/admin/organisations/3950/lieux/24790/edit

L'adresse est : 19 **bis** Rue aux Boeufs, Bernay, 27300

**Comment by Michaelvilleneuve** [comment]
C'est fait 👍 
<img width="370" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/bf70acb1-b1c7-4a7c-84dc-5b41f171c8ec">
