### ISSUE TITLE
[Bug] Impossible de créer un conjoint

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1358]
Monsieur existe (conjoint) https://www.rdv-insertion.fr/departments/26/applicants/57067
Madame ne partage pas le mm ID local mais uniquement les données de contacts. : L B  DEM 42744 numéro NIR en 2. 
Pourtant, la création est impossible.

**Comment by aminedhobb** [comment]
@ClaireCasu on ne devrait pas afficher les données ici :)
