### ISSUE TITLE
[Suite Drôme] Renvoyer une invitation lorsqu'un bénéficiaire annule son rdv

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#136]
Lorsqu'un bénéficiaire annule son RDV, il ne peut plus utiliser le lien d'invitation.
Cette issue propose de renvoyer directement un mail et/ou un sms comportant un nouveau lien d'invitation, dès l'annulation du RDV.

Une fois que cette feature sera opérationnelle, on proposera au CD26 de modifier le message d'avertissement qui apparaît lors de l'annulation dans RDV-Solidarités, pour que celui-ci explique qu'une invitation va de nouveau être faite.

**Comment by aminedhobb** [comment]
lié à #197
