### ISSUE TITLE
[MAJ RDV ] RDV "absence non excusée" à RDV "honoré"

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1452]
**USER ID 46409** sur la Loire Atlantique orga St Nazaire il y avait un doublon sur rdv -i que j'ai desaffecté de l'orga et il a donc disparu. Possibilité de fusionner les 2 fiches usagers pour avoir l'historique de ses rdv stp ? Un rdv absnece non excusée au 04/07 et un RDV honoré au 01/08.

**Comment by aminedhobb** [comment]
ça devrait être bon @Evajuliab 👍
