### ISSUE TITLE
[VAR] Rajouter l'équipe produit/bizdev sur tout le VAR

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1472]
Est ce que vous pouvez rajouter : Claire, Amaury, Eva, Salma sur toutes les orgas du VAR en admin svp ?

**Comment by ClaireCasu** [comment]
On le fait avec l'autre ticket (pour toutes orgas) : https://github.com/betagouv/rdv-insertion/projects/1#card-89786900
