### ISSUE TITLE
[Tags] - Réinitialiser les tags après recherche

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1483]
**Comportement observé**
Lorsqu'un agent filtre par tags et souhaite revenir à la liste initiale il doit cliquer sur la liste de "tous les contacts"

**Comportement souhaité**
Avoir un bouton pour réinitialiser les tags directement sur la page des résultats

(demande du 44)

**Comment by Michaelvilleneuve** [comment]
Je pense que ce problème ne sera plus trop d'actualité une fois déployé la dernière version : 
<img width="544" alt="image" src="https://github.com/betagouv/rdv-insertion/assets/4990201/11528d31-9d9d-48d7-a5ec-ed181bfaa0ef">

Puisque les filtres par tag sont intégré comme les autres il suffit de clicker sur "Retour à la liste"
