### ISSUE TITLE
[Stats Comité] Pour calculer des indicateurs d'impact, nous avons besoins de quelques chiffres en base

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1498]
_Pour chaque indicateur_ : 
- Sont d'abord décrits la période à prendre en compte, le périmètre usagers, contextes et organisations à prendre en compte ; 
- Puis sont décrites les requêtes en tant que telle à produire. 

# :fire: Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv RSA"

**Période** : mai - octobre 2023 

**Périmètre des usagers concernés** : tous les usagers ayant un rendez-vous positionné sur cette période, qu'il ait été pris en autonomie après invitation ou qu'il ait été positionné par convocation. 

**Périmètre des contextes concernés** : tous les contextes RSA, soit : 
- rsa_integration_information
- rsa_droits_devoirs
- rsa_orientation
- rsa_orientation_file_active
- rsa_orientation_france_travail
- rsa_orientation_coaching
- rsa_orientation_freelance
- rsa_orientation_on_phone_platform
- rsa_accompagnement
- rsa_accompagnement_social
- rsa_accompagnement_sociopro
- rsa_accompagnement_moins_de_30_ans
- rsa_follow_up
- rsa_suivi_plie
- rsa_cer_signature
- rsa_insertion_offer
- rsa_atelier_competences
- rsa_atelier_rencontres_pro
- rsa_atelier_collectif_mandatory
- rsa_main_tendue
- rsa_spie

**Périmètre des structures concernées** : toutes les organisations qui évoluent sur un des contextes RSA et qui appartiennent donc aux territoires suivants : 
- 01 - Ain
- 08 - Ardennes
- 12 - Aveyron
- 13 - Bouches-du-Rhône
- 23 - Creuse
- 26 - Drôme
- 27 - Eure
- 44 - Loire-Atlantique
- 45 - Loiret
- 48 - Lozère
- 50 - Manche
- 54 - Meurthe-et-Moselle
- 55 - Meuse
- 63 - Oise
- 64 - Pyrénées-Atlantiques
- 69 - Rhône
- 74 - Haute-Savoie
- 78 - Yvelines
- 81 - Tarn
- 83 - Var
- 84 - Vaucluse
- 88 - Vosges
- 93 - Seine-Saint-Denis

**Requête 1** : nombre de rdv organisés / positionnés 

**Requête 2** : Nombre de rdv honorés

# :fire: Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv SIAE 

**Période** : mai - octobre 2023 

**Périmètre des usagers concernés** : tous les usagers ayant un rendez-vous positionné sur cette période, qu'il ait été pris en autonomie après invitation ou qu'il ait été positionné par convocation. 

**Périmètre des contextes concernés** : tous les contextes SIAE, soit : 
 - siae_interview
 - siae_collective_information
 - siae_follow_up

**Périmètre des structures concernées** : toutes les organisations qui évoluent sur un des contexte SIAE, soit : 
- 120	SBC Insertion
- 144	ACI Neptune
- 145	Ladomifa
- 151	Clarisse Environnement
- 160	Laser Emploi Auvergne
- 162	AIPLM
- 163	Envie
- 164	La Chiffo - Association ACIADES
- 165	Association La Verdinière
- 168	Travailler en moselle
- 174	LA RESSOURCE AAA
- 194	Ecleepse
- 201	ULISSE INTERIM
- 202	Humando
- 203	Hygie Sphère Montpellier
- 204	Hygie Sphère Béziers
- 205	REVIE - VERRE
- 207	Envie 2E Poitou-Charentes
- 208	Au lavoir
- 209	TREMPLIN 52
- 213	RE EMPLOI
- 215	ENSOVO
- 216	ASPIRE Service
- 241	ISA INTERIM Auch
- 243	ISA INTERIM L’Isle-jourdain
- 244	Courtoise Ressourcerie Brignoles
- 245	Ligue de l’enseignement 31
- 246	TEF DU CINGAL
- 250	CCAS Hirson
- 242	Espérer 95

**Requête 1** : nombre de rdv organisés / positionnés 

**Requête 2** : Nombre de rdv honorés

# :fire: Pour l'indicateur "Taux d'entrée RSA 1"

**Période** : mai - octobre 2023 

**Périmètre des usagers concernés** : tous les usagers ayant eu un rendez-vous d'orientation RSA honoré et qui sont par ailleurs gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".

**Périmètre des contextes concernés** : les contextes RSA orientation et accompagnement, soit : 
- rsa_orientation
- rsa_orientation_file_active
- rsa_orientation_france_travail
- rsa_orientation_coaching
- rsa_orientation_freelance
- rsa_orientation_on_phone_platform
- rsa_accompagnement
- rsa_accompagnement_social
- rsa_accompagnement_sociopro
- rsa_accompagnement_moins_de_30_ans
- rsa_follow_up
- rsa_suivi_plie
- rsa_cer_signature

**Périmètre des structures concernées** : les CD qui travaillent à la fois sur l'orientation et l'accompagnement, soit : 
- 08 - Ardennes
- 26 - Drôme
- 45 - Loiret
- 83 - Var

Requête 1 : nombre de bénéficiaires ayant eu à la fois un rendez-vous d'orientation RSA honoré et qui sont également gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".

Requête 2 : nombre de bénéficiaires ayant eu à la fois un rendez-vous d'orientation RSA honoré et et ayant également eu un rendez-vous RSA accompagnement honoré moins de 30 jours après le rendez-vous d'orientation.

# :fire: Pour calculer l'indicateur "Taux d'entrée RSA 2"

**Période** : mai - octobre 2023 

**Périmètre des usagers concernés** : tous les usagers ayant été *invités* sur un contexte d'orientation RSA et qui sont par ailleurs gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".

**Périmètre des contextes concernés** : les contextes RSA orientation et accompagnement, soit : 
- rsa_orientation
- rsa_orientation_file_active
- rsa_orientation_france_travail
- rsa_orientation_coaching
- rsa_orientation_freelance
- rsa_orientation_on_phone_platform
- rsa_accompagnement
- rsa_accompagnement_social
- rsa_accompagnement_sociopro
- rsa_accompagnement_moins_de_30_ans
- rsa_follow_up
- rsa_suivi_plie
- rsa_cer_signature

**Périmètre des structures concernées** : les CD qui travaillent à la fois sur l'orientation et l'accompagnement, soit : 
- 08 - Ardennes
- 26 - Drôme
- 45 - Loiret
- 83 - Var

Requête 1 : nombre de bénéficiaires ayant été à la fois invités dans un contexte d'orientation RSA et qui sont également gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".

Requête 2 : nombre de bénéficiaires ayant été à la fois invités dans un contexte d'orientation RSA et et ayant également eu un rendez-vous RSA accompagnement honoré moins de 30 jours après le rendez-vous d'orientation.

# :fire: Pour calculer l'indicateur "Taux de décrochage RSA" - Seine Saint Denis

**Période** : mai - octobre 2023 

**Périmètre des usagers concernés** : tous les usagers ayant été invités a minima sur un contexte. 

**Périmètre des contextes concernés** : 
- rsa_accompagnement
- rsa_accompagnement_moins_de_30_ans
- rsa_follow_up
- rsa_suivi_plie
- rsa_cer_signature
- rsa_insertion_offer

**Périmètre des structures concernées** : 
- ALI de Pantin (ID rdv-insertion `27`). 

Requête 1 : nombre de bénéficiaires ayant eu une invitation initiale dans n'importe quel contexte utilisé par l'ALI de Pantin.

Requête 2 : nombre de bénéficiaires ayant eu une invitation initiale dans n'importe quel contexte utilisé par l'ALI de Pantin et qui n'ont eu aucun rendez-vous honoré sur la période de six mois.

**Comment by Michaelvilleneuve** [comment]
## 🔥 Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv RSA"

Requêtes : 
```ruby
period_min = "2023-05-01"
period_max = "2023-11-01"
departments = ["01", "08", "12", "13", "23", "26", "27", "44", "45", "48", "50", "54", "55", "63", "64", "69", "74", "78", "81", "83", "84", "88", "93"]
motifs = [ "rsa_integration_information", "rsa_droits_devoirs", "rsa_orientation", "rsa_orientation_file_active", "rsa_orientation_france_travail", "rsa_orientation_coaching", "rsa_orientation_freelance", "rsa_orientation_on_phone_platform", "rsa_accompagnement", "rsa_accompagnement_social", "rsa_accompagnement_sociopro", "rsa_accompagnement_moins_de_30_ans", "rsa_follow_up", "rsa_suivi_plie", "rsa_cer_signature", "rsa_insertion_offer", "rsa_atelier_competences", "rsa_atelier_rencontres_pro", "rsa_atelier_collectif_mandatory", "rsa_main_tendue", "rsa_spie" ]

# Nombre de RDVs positionnés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(departments: { number: departments })
  .count



# Nombre de RDVs honorés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(departments: { number: departments })
  .where(status: "seen")
  .count
```

**Comment by Michaelvilleneuve** [comment]
## 🔥 Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv SIAE

Requêtes
```ruby
period_min = "2023-05-01"
period_max = "2023-11-01"
organisations = [ 120, 144, 145, 151, 160, 162, 163, 164, 165, 168, 174, 194, 201, 202, 203, 204, 205, 207, 208, 209, 213, 215, 216, 241, 243, 244, 245, 246, 250, 242, ]
motifs = [ "siae_interview", "siae_collective_information", "siae_follow_up"]

# Nombre de RDVs positionnés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(:organisation)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(organisations: { id: organisations })
  .count



# Nombre de RDVs honorés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(organisations: { id: organisations })
  .where(status: "seen")
  .count
```

**Comment by Michaelvilleneuve** [comment]
## Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv RSA"
```ruby
period_min = "2023-05-01"
period_max = "2023-11-01"
departments = ["01", "08", "12", "13", "23", "26", "27", "44", "45", "48", "50", "54", "55", "63", "64", "69", "74", "78", "81", "83", "84", "88", "93"]
motifs = [ "rsa_integration_information", "rsa_droits_devoirs", "rsa_orientation", "rsa_orientation_file_active", "rsa_orientation_france_travail", "rsa_orientation_coaching", "rsa_orientation_freelance", "rsa_orientation_on_phone_platform", "rsa_accompagnement", "rsa_accompagnement_social", "rsa_accompagnement_sociopro", "rsa_accompagnement_moins_de_30_ans", "rsa_follow_up", "rsa_suivi_plie", "rsa_cer_signature", "rsa_insertion_offer", "rsa_atelier_competences", "rsa_atelier_rencontres_pro", "rsa_atelier_collectif_mandatory", "rsa_main_tendue", "rsa_spie" ]

# Nombre de RDVs positionnés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(departments: { number: departments })
  .count


=> 49160


# Nombre de RDVs honorés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(departments: { number: departments })
  .where(status: "seen")
  .count

=> 34610
```

## Pour calculer l'indicateur "Taux moyen d'absentéisme aux rdv SIAE


```ruby
organisations = [ 120, 144, 145, 151, 160, 162, 163, 164, 165, 168, 174, 194, 201, 202, 203, 204, 205, 207, 208, 209, 213, 215, 216, 241, 243, 244, 245, 246, 250, 242]
motifs = [ "siae_interview", "siae_collective_information", "siae_follow_up"]

# Nombre de RDVs positionnés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(:organisation)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(organisations: { id: organisations })
  .count

=> 603


# Nombre de RDVs honorés
Rdv
  .where("starts_at > ?", period_min)
  .where("starts_at < ?", period_max)
  .joins(organisation: :department)
  .joins(motif: :motif_category)
  .where(motif_categories: { short_name: motifs })
  .where(organisations: { id: organisations })
  .where(status: "seen")
  .count

=> 305
```

## Pour l'indicateur "Taux d'entrée RSA 1"

```ruby
departments = ["08", "26", "45", "83"]
motifs = [ "rsa_orientation", "rsa_orientation_file_active", "rsa_orientation_france_travail", "rsa_orientation_coaching", "rsa_orientation_freelance", "rsa_orientation_on_phone_platform", "rsa_accompagnement", "rsa_accompagnement_social", "rsa_accompagnement_sociopro", "rsa_accompagnement_moins_de_30_ans", "rsa_follow_up", "rsa_suivi_plie", "rsa_cer_signature", ]


# nombre de bénéficiaires ayant été à la fois invités dans un contexte d'orientation RSA et qui sont également gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".
User
  .joins(:rdvs, :motif_categories, :departments, :rdv_contexts)
  .where("rdvs.starts_at > ?", period_min)
  .where("rdvs.starts_at < ?", period_max)
  .where("rdv_contexts.status != 0")
  .where(rdvs: { status: "seen" })
  .where(motif_categories: { short_name: motifs })
  .where(departments: { number: departments })
  .count

=> 260797
```

**Comment by ClaireCasu** [comment]
Michael, pour le Taux d'entrée RSA, vu qu'il y a deux propositions de calcul (taux d'entrée RSA 1 et 2): si jamais un des modes de calcul "tourne" et pas l'autre, ce n'est pas forcément la peine de passer du temps pour l'autre.

**Comment by Michaelvilleneuve** [comment]
> Michael, pour le Taux d'entrée RSA, vu qu'il y a deux propositions de calcul (taux d'entrée RSA 1 et 2): si jamais un des modes de calcul "tourne" et pas l'autre, ce n'est pas forcément la peine de passer du temps pour l'autre.

Celle-ci tourne 
```
# nombre de bénéficiaires ayant été à la fois invités dans un contexte d'orientation RSA et qui sont également gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".
```

Le truc plus complexe à calculer c'est ça `et ayant également eu un rendez-vous RSA accompagnement honoré moins de 30 jours après le rendez-vous d'orientation.` et les deux méthodes de calcul en ont besoin si je ne me trompe pas. 

Les requêtes "1" de Taux RSA 1 & 2 tournent bien. Ça ne suffit pas du coup ?

**Comment by ClaireCasu** [comment]
Eh non - ça nous donne à chaque fois uniquement le dénominateur (pour les deux méthodes). En tout cas, c'est uniquement pour de l'interne, pour nous donner des ordres de grandeur (pour notre atelier de mercredi prochain) - donc si ça te prend trop de temps ce n'est pas la peine. Mais si c'est en lien avec la mise à jour des stats publiques sur notre site, alors c'est chouette !

**Comment by Michaelvilleneuve** [comment]
> Eh non - ça nous donne à chaque fois uniquement le dénominateur (pour les deux méthodes). En tout cas, c'est uniquement pour de l'interne, pour nous donner des ordres de grandeur (pour notre atelier de mercredi prochain) - donc si ça te prend trop de temps ce n'est pas la peine. Mais si c'est en lien avec la mise à jour des stats publiques sur notre site, alors c'est chouette !

Non mais de toute façon il faut régler ce problème de RAM même pour le prod donc ça solutionnera aussi cette requête :+1:

**Comment by Michaelvilleneuve** [comment]
@ClaireCasu J'ai recalculé la requête 2 du taux d'entrée RSA 1, voici ce que je trouve : 

115273 usagers ayant eu un RDV d'orientation honoré
Dont 5607 ayant également eu un rdv d'accompagnement dans les 30 jours suivants

**Comment by ClaireCasu** [comment]
Merci beaucoup Michael ! 
Et le taux d'entrée RSA 2 ne fonctionne pas?

**Comment by Michaelvilleneuve** [comment]
@ClaireCasu Si si il fonctionnera de la même manière il faut juste que je me remette dessus (je suis en train de voir pourquoi la DB crash sur les stats de prod) je me remet dessus rapidement 👍

**Comment by ClaireCasu** [comment]
Top trop bien ! 
Pardon j'ai juste un doute; ce que tu as recalculé c'était le taux d'entrée RSA 1? Donc le 260797 qui est plus haut n'est plus valable?

**Comment by Michaelvilleneuve** [comment]
@ClaireCasu Je te confirme que le premier calcul plus haut était bien une erreur (j'avais fait un OR au lieu d'un AND pour les motifs catégories). 

Pour récapituler :

### RSA 1 : 
Je trouve **115000 (un peu plus maintenant)** usagers qui sont en RDV orientation honoré, parmi eux : 
 - 13311 sont aussi gérés dans un contexte d'accompagnement avec un statut différent de "Non invité".
- 5607 ont également eu un RDV d'accompagnement honoré dans les 30 jours suivants


### RSA 2 : 
Je trouve **152727 usagers** qui ont été invités dans un contexte d'orientation RSA, parmi eux : 

- 14264 sont également gérés dans un contexte d'accompagnement avec un statut différent de "Non invité" (Requête 1)
- [encore en train de tourner] ont eu un rendez-vous RSA accompagnement honoré moins de 30 jours après le rendez-vous d'orientation (Requête 2)

**Comment by ClaireCasu** [comment]
Merci Michael !
