### ISSUE TITLE
Etudier la faisabilité de l'envoi du courrier sur RDVI pour les Ardennes

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#155]
Pour les allocataires sans mail ni numéro de téléphone: deux possibilités:

- **Solution A** (intermédiaire): 
1. rajouter un bouton dans la page d'invitation des allocataires, qui permet de créer un courrier en PDF, qui contient le code d'invitation + l'adresse du bénéficiaire + le nom du référent
2. permettre de visualiser ce courrier pour que Isabelle puisse vérifier 
3. rajouter un autre bouton "télécharger tous les courrier" qui permet de télécharger **en 1 fois** sur un même **document pdf** tous les courriers générés dans cette vague d'orientation
4. ensuite Isabelle va déposer ce fichier sur son fichier excel Maileva

- **Solution B** (plus pérenne):
1. rajouter un bouton "envoyer le courrier" dans la page d'invitation des allocataires qui appelle directement l'[API Maileva](https://www.maileva.com/developpeur/detail?id=282) 
Questions: comment savoir que le courrier est bien parti? Comment savoir que les données d'entrées sont les bonnes?

Claire et Amaury demandent aux départements en embarquement si une solution courrier de ce type pourrait les intéresser en parallèle

**Comment by qblanc** [comment]
A mon avis, l'option A serait la plus rapide à mettre en place et la plus standard pour tous, mais pour faire un truc vraiment standard je pense qu'il faut se limiter à : un bouton "Inviter par courrier" qui entraîne le téléchargement d'un pdf personnalisé pour l'allocataire, en fonction du template du département (donc => une seule étape plutôt que 2 pour arriver au téléchargement). Fusionner leurs pdfs en un seul pour les envoyer est une manip qu'ils peuvent faire de leur côté je pense, car c'est simple et tous n'en auront pas forcément besoin.

La solution B pourra être mise en place dans un second temps => Au lieu de générer le téléchargement d'un pdf, le bouton entraîne l'envoi direct du courrier via API. Le comportement du bouton "Inviter par courrier" pourra être différent selon les départements (certains conservent l'option A, d'autres basculent sur l'option B) en fonction de leur configuration. Cette option B nécessitera peut-être des développements + custom en fonction des départements, car tous n'utilisent peut-être pas la même API d'envoi de courrier.
