### ISSUE TITLE
[Bug- Meuse 55] - Envoi invitations impossible 

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1557]
**Comportement observé**
Impossible de générer les courriers d'invitations pour l'orientation RSA car message d'erreur de créneaux indispos alors que des créneaux sont bien disponibles sur l'orga. 

<img width="1426" alt="Capture d’écran 2023-11-23 à 10 10 48" src="https://github.com/betagouv/rdv-insertion/assets/103074596/59fed8aa-3c01-45f5-966c-72c8432a71aa">

**Comment by aminedhobb** [comment]
@Evajuliab on peut fermer ce ticket du coup ?
