### ISSUE TITLE
[Création territoire] Créer le territoire du Cantal en démo sur rdv-insertion 

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1558]
Pour que le Cantal puisse faire les tests sur l'API, il faut qu'on leur donne accès à un espace de démo.

**Comment by aminedhobb** [comment]
Le territoire est créé sur rdv-s. Il faut bien juste créer le département sur RDV-I ? Tu veux aussi que je crée l'orga ?

**Comment by aminedhobb** [comment]
Je vois que c'est déjà fait, je ferme le ticket du coup :)

**Comment by ClaireCasu** [comment]
Parfait merci !
