### ISSUE TITLE
Etudier la faisabilité de l'ajout du nom du référent dans nos messages

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#156]
Feature demandée par les Ardennes et la Drôme.
L'idée serait de rajouter le nom du référent dans nos messages et de renvoyer uniquement vers l'agenda de celui-ci.

**Comment by qblanc** [comment]
Je remonte cette issue dans le backlog car cela suit la même logique que la demande de la Manche (mail du 27 juillet de Karine Montmirel). Un peu différent de ce qu'il y a actuellement dans l'EPIC #507, mais peut sans doute y être relié.
