### ISSUE TITLE
[Page Statistiques] MAJ la page statistiques avec le nombre d’usagers suivis par mois 

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1565]
**User story**
En tant que membre de l'équipe rdv-insertion, je veux savoir le nombre de bénéficiaires qui ont été mis en relation par mois afin que je puisse comparer mes statistiques à celles des autres produits du GIP Plateforme de l'inclusion

**Description technique**
Sur la page statistique, je n'ai aucune idée du nombre d'usagers qui ont eu un rendez-vous (rendez-vous honoré) ou qui ont pris un rendez-vous / pour qui ont a pris un rendez-vous (rendez-vous pris à venir) par mois. Il faudrait pouvoir connaitre le nombre d'usagers qui ont au moins un rdv de programmé par mois.

Pour cela, il faudrait prendre en compte : l'ensemble des usagers du mois qui ont au moins un rdv pris ou un rdv honoré.

Le calcul : 
usagers uniques dans toutes les listes avec statut du rdv pris ou honoré ; dans le mois

**Comment by adenoix** [comment]
Des news @SalmaBennani ?

**Comment by SalmaBennani** [comment]
@adenoix On met ce ticket dans le prochain sprint. Il faudra juste trancher sur la question de mises en relation : on prend uniquement les rdv honorés ou bien on compte aussi les personnes avec un rdv à venir (car il s'agit "déjà" d'une mise en relation). 

Perso, je disais que mettre en relation veut dire "contacté en prévision d'un rdv" ou "rdv effectué déjà dans le mois". Sachant qu'on parle d'un usager, si dans le mois il a été contacté et a eu son rdv, il ne sera comptabilisé qu'une fois

@ClaireCasu @amaurydubot vous en pensez quoi ?

**Comment by ClaireCasu** [comment]
Je suis d'accord avec "on prend uniquement les rdv honorés ou bien on compte aussi les personnes avec un rdv à venir (car il s'agit "déjà" d'une mise en relation)" : du coup pour moi ça se traduit par la prise en compte des personnes avec statut du rdv = rdv pris, rdv honoré (sans les "en attente").

On prend en compte toute personne qui a un rdv honoré ou à venir (car les "en attente" n'ont pas encore fait une action donc je me dis qu'elles sont pas en relation)
