### ISSUE TITLE
[Bug - Drôme 26] Ajout d'un usager à une organisation 

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1575]
**Comportement observé**
Impossible d'ajouter un bénéficiaire à une organisation depuis l'upload du ficher xl alors que je peux l'ajouter manuellement à l'organisation en question en me rendant sur la fiche du bénéficiaire depuis son orga d'origine.

<img width="1096" alt="Capture d’écran 2023-11-29 à 11 36 38" src="https://github.com/betagouv/rdv-insertion/assets/103074596/899e5eac-df91-453f-946d-530ace2a0565">

**Comportement souhaité**
Pouvoir ajouter à l'organisation dans lequel il est importé sans message d'erreur

**Comment by aminedhobb** [comment]
## Raison technique

Pour les demandeurs/conjoints partageant les mêmes numéros/email la validation échoue logiquement ici: https://github.com/betagouv/rdv-insertion/blob/760621eaa84a7a27d9402bc080be6ef28bfc308e/app/services/users/validate.rb#L11

On ne devrait pas faire ces validations sur les demandeurs/conjoints.

### Remarque

Pas lié à ce problème directement mais lorsqu'on ajoute à l'organisation on fait un `users#create` et pas un `users#update`, il me semble que j'avais fait ça pour des questions d'autorisation mais à voir si c'est toujours pertinent

**Comment by aminedhobb** [comment]
Les rôles n'étaient pas les mêmes entre le fichier et la BDD d'où l'incohérence
