### ISSUE TITLE
[Bug] - Erreur 404 assignation d'un référent 

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1622]
**Comportement observé**
Erreur 404 lors de l'assignation d'un référent à un usager sur RDVI à l'import. Impossible aussi de sélectionner un référent depuis la fiche usager. 

<img width="1423" alt="Capture d’écran 2024-01-02 à 16 06 57" src="https://github.com/betagouv/rdv-insertion/assets/103074596/e81fb1a2-1f45-4b77-828d-cf68d915d250">

<img width="1427" alt="Capture d’écran 2024-01-02 à 16 07 12" src="https://github.com/betagouv/rdv-insertion/assets/103074596/4126cd08-edad-4eeb-8b7b-a4e5ab2062ad">

<img width="1440" alt="Capture d’écran 2024-01-02 à 16 20 10" src="https://github.com/betagouv/rdv-insertion/assets/103074596/408b1ed8-5904-4382-947b-0dae991ccc9a">

**Comment by Michaelvilleneuve** [comment]
Je ferme suite au dernier fix https://github.com/betagouv/rdv-insertion/pull/1626
