### ISSUE TITLE
[Export CSV] changement contenu d'une colonne dans l'export usager

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1702]
**User story**
Dans l'export .csv des usagers, en tant qu'agent je veux voir apparaitre la vraie date d'orientation (aujourd'hui on indique la date du premier rendez-vous + on indique des dates d'orientation issues d'autres territoires). 

**Solution**

Indiquer la date d'orientation qui est déterminée de la sorte : c'est la date du rendez-vous honoré relevant d'une catégorie d'orientation (ex : RSA orientation, RSA orientation France Travail, etc.) au sein d'un territoire déterminé (ne pas prendre la date issue d'un autre territoire que celui de l'organisation de l'agent effectuant l'export).

**Comment by Michaelvilleneuve** [comment]
Pour info ce changement risque de ralentir un peu plus l'export CSV car il implique une recherche assez profonde pour chaque user exporté. Rien de grave d'autant qu'on l'envoi par mail mais il faut en avoir conscience.
