### ISSUE TITLE
[Bug] La sectorisation sur la prescription interne du VAR ne semble pas bien fonctionner

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1731]
**Comportement observé**
La prescription interne du Var repose sur la sectorisation pour pousser les lieux + motifs de rdv qui sont dans le même secteur que l'usager. Le prescripteur part de la fiche de l'usager sur laquelle il y a son adresse puis le logiciel pousse les motifs ouverts à la prescription dans le même secteur de l'usager basée sur son adresse.

Il semble y avoir un souci sur le fait que ça fonctionne correctement. Nous avons 2 individus qui sont dans le même secteur mais qui n'ont pas accès aux mêmes motifs : 
- User 1 : https://www.rdv-solidarites.fr/admin/organisations/3677/users/918813
- User 2 : https://www.rdv-solidarites.fr/admin/organisations/3677/users/776619

**Comportement souhaité**
Étant donné que les 2 sont dans le même secteur, il faudrait qu'ils puissent voir les mêmes motifs

**Comment by qblanc** [comment]
Comme expliqué par @Holist, le comportement est normal. Le sujet sera géré par l'équipe bizdev/support.
