### ISSUE TITLE
[Suppression organisation] id 4199 / 302

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1764]
A la demande des Yvelines, il faudrait supprimer l'organisation test que nous avions mis en prod pour besoin de leur formation en janvier 24 svp

Orga id RDVSP 4199 - Organisation test pour la formation
Orga id RDVI  302

**Comment by SalmaBennani** [comment]
Après échange avec les Yvelines, ce qu'ils veulent réellement, c'est ne pas avoir cette orga en incidence sur leurs stats et exports csv. Ils veulent néanmoins garder cette orga pour les prochaines formations.

Est-ce que si on supprime juste les usagers ça fait l'affaire ?

Sinon, on leur crée une plateforme en démo et on leur partage les urls + donnent les accès (je trouve que ça les perd des fois les 2 urls une fois la formation finie, ils ne savent plus où aller). C'ets peut-être moins lourd comme gestion !

**Comment by Holist** [comment]
Si on supprime les données de l'organisation (usagers et invitations et rdvs) il n'y aura plus rien dans les stats et les exports. Cela dit je serai plus à l'aise de faire les démos sur l'environnement de démo et tout transférer dessus même si le travail est plus important... Est ce que la seule difficulté dans le process vient de l'url ? 
Pourtant c'est assez clair https://www.rdv-insertion-demo.fr/ ...
@SalmaBennani qu'en penses tu ?

**Comment by SalmaBennani** [comment]
Yes, je créerai une plateforme de démo, tu peux supprimer l'orga @Holist Merci 🙏

**Comment by Holist** [comment]
C'est fait.
