### ISSUE TITLE
[Bug] - Diagnostics et contrat fichier >5Mo

### ISSUE THREAD

**Issue by samanthaauffret** [betagouv/rdv-insertion#1823]
**Comportement observé**
Lorsque je télécharge un gros fichier diagnostics et contrats (>5Mo), le dossier usager se recharge en me plaçant sur l'onglet "infos". Je ne comprend pas que c'est la taille du fichier qui pose soucis

**Comportement souhaité**
Si un fichier à télécharger est trop lourd, indiquer à l'utilisateur un message d'erreur lui rappelant que la taille de fichier ne doit pas excéder les 5 Mo.

**Comment by aminedhobb** [comment]
@samanthaauffret en re-testant chez moi le message d'erreur apparait bien (au bout de qq secondes quand même). 
Mais c'est quand même bizarre le comportement que tu observes. 
Par contre il est d'usage de ne pas assigner de dev avant le sprint planning, à part si la priorité du ticket est P0 et que l'on assigne le dev de vigie. 
Je me permets donc de le désassigner même si je comprends pourquoi tu voulais l'assigner :)

**Comment by samanthaauffret** [comment]
Ah d'accord, merci pour l'info sur l'assignation je ne savais pas :)
