### ISSUE TITLE
[INDEX] - Mettre en place la pagination du DSFR sur RDVI

### ISSUE THREAD

**Issue by samanthaauffret** [betagouv/rdv-insertion#1830]
## 🚀 Objectif de l'EPIC

En tant qu'utilisateur, je souhaite naviguer rapidement dans les pages de la fonctionnalité "Liste des usagers". 
-> Revenir à la première page
-> Aller à la dernière page
-> Aller sur la page X 
-> Passer d'une page à la suivante
-> Revenir à la page précédente
-> Me rendre compte du nombre de pages d'usagers que nous avons dans notre base RDVI. 

## ❓ Définition du problème

Aujourd'hui la pagination est discrète graphiquement et ses zones de clic assez étroites. Il lui manque quelques éléments pour en faire une pagination complète : 

![image](https://github.com/betagouv/rdv-insertion/assets/156072816/cde45fe3-b12f-4752-831b-66567e2d7a38)

Relevé durant l'audit UX T1 2024

## 🏅 Définition de la solution proposée

Remplacer la pagination actuelle pas la pagination du DSFR, qui a été pensée dans les cas de gros volumes de pages. 
Pour éviter un patchwork de styles graphiques, il faut mettre cette nouvelle pagination au style de RDVI : 
-> Mettre le bleu RDVI
-> Mettre un border-radius comme les CTA RDVI 
-> Mettre la même typo que RDVI 

Maquette disponible sur figma : 
https://www.figma.com/file/Cz06mc5npAnTWujPJAC5fq/LISTE-USAGERS-(Page-Index)?type=design&node-id=1%3A15&mode=design&t=6IMI3P5CQeyOIuMV-1

<img width="1216" alt="Frame 3" src="https://github.com/betagouv/rdv-insertion/assets/156072816/38f6bfeb-bab2-4329-bf20-f569a39ea3c3">

SPRINT PLANNING 21/03 : En profiter pour se repencher sur le DSFR : voir si c'est opportun d'en profiter pour embarquer une partie / un composant du DSFR ou bien rester pour l'instant sur un dev custom pour ce ticket.

## 📊  Qualification de l'impact avec la méthode RICE

**R**each - 10 - tous les utilisateurs ayant plus d'une page sur RDVI

**I**mpact (1/2/3) - Fluidifier la navigation et s’harmoniser avec les autres sites Beta et GIP
1 : l'EPIC apporte une amélioration à l'existant

**C**onfidence (1/2/3)- 3

**E**ffort (S/M/L/XL) : quel est l'effort de développement estimé ?
Taille	Estimation dev + review + correction bug (jours)
XL	16
L	8
M	4
**S	1** > supposé : besoin de refinement

**Comment by Holist** [comment]
L'import des feuilles de style DSFR a des effets de bords importants sur le style existant et l'import d'une seule partie du css du dsfr me semble une mauvaise idée (500+ lignes de CSS juste pour la pagination et le faire fonctionner avec kaminari demanderai plus de temps que ce que l'on souhaite accorder à ce ticket (à mon avis)
Je pars sur un composant 'custom'.
