### ISSUE TITLE
[TAGS] - Ignorer la casse lors de l'import des tags par fichier

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#1862]
**Comportement observé**
L'outil est sensible à la casse lors de l'import des tags depuis le fichier Excel. Je propose qu'on ignore la casse voire même la reconnaissance des X premières lettres du tag créé sur l'organisation pour éviter toute erreur ou blocage d'import.

**Comportement souhaité**

**Comment by Michaelvilleneuve** [comment]
Pour info je m'apprétais à uniformiser l'ensemble de l'affichage des tags dans le produit pour appliquer une règle où seule la première lettre est en majuscule mais il s'avère que c'est impossible et non souhaitable car beaucoup de tags en production ne sont pas juste un mot. 
Quelques exemples : 
"Arrêt maladie/maternité"
"Non soumis droits & devoirs"
"Droit RSA suspendu"

Ce serait donc étrange d'avoir "Droit Rsa Suspendu" ou même tout en majuscule. 

Ce que je propose donc c'est uniquement de faire le matching lors de l'ajout d'un fichier mais de laisser le reste des visuels inchangés.
