### ISSUE TITLE
[Bug] Impossible de créer 2 usagers qui ont les mêmes coordonnées sur la Meuse

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#1881]
**Comportement observé**
Un couple d'usagers au niveau de la Meuse ont : 

- les mêmes coordonnées
- le même ID CAF

Lorsqu'on essaie d'intégrer les 2, en indiquant au niveau du rôle "demandeur" pour l'une et "conjoint" pour l'autre, le logiciel fusionne automatiquement les fiches.

**Comportement souhaité**
Un couple avec les mêmes coordonnées peut avoir 2 fiches différentes si on attribue un rôle différent à chacun

**Comment by aminedhobb** [comment]
@SalmaBennani , les IDs CAF dans un couple sont toujours les mêmes, et l'appli est justement faite pour qu'un couple - qui a donc les mêmes coordonnées de contact et les mêmes ID CAF - puisse être créé sans souci si l'un est demandeur et l'autre conjoint.
Dans ce cas précis, le problème vient du fait que le demandeur et le conjoint ont le même prénom.
C'est un cas rare (première fois que ça arrive il me semble) mais ça mérite effectivement un fix.

**Comment by aminedhobb** [comment]
On a finalement créé l'usager en question et décidé de ne pas faire de fix généralisé (voir https://mattermost.incubateur.net/betagouv/pl/qtmhhoiex7rbbp5mic8r4cwmcy et #1907 )
