### ISSUE TITLE
[Bug] - En tant qu'utilisateur "basique", je vois le cta "configuration de l'organisation"

### ISSUE THREAD

**Issue by samanthaauffret** [betagouv/rdv-insertion#1899]
**Comportement observé**
En testant le RDVI d'une gestionnaire, j'ai vu qu'elle avait le CTA "configurer l'organisation" était visible sur son interface mais au clic, elle n'avait pas accès à la fonctionnalité. Un message jaune s'est affiché en haut de la page liste et il indiquait qu'elle n'avait pas les droits. 

J'ai essayé de reproduire le cas en démo avec un compte basique, mais j'ai pu accéder à la fonctionnalité. (fonctionnalité plus restreinte qu'un profil user administrateur)

**Comportement souhaité**
Pouvoir accéder à la fonctionnalité "configurer l'organisation" en tant que profil user "basique" en mode fonctionnalité restreinte 
ou 
ne pas afficher le CTA "configurer l'organisation" aux profils user "basique"

**Comment by samanthaauffret** [comment]
@amaurydubot tu peux m'indiquer le comportement qui est souhaité dans le cas décrit ci-dessus ?

**Comment by qblanc** [comment]
ticket doublon de #1925
