### ISSUE TITLE
[statistiques] Calculer les mises en relation pour le comité 

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1910]
Pour le comité, il faudrait calculer les mises en relation, conformément à la **première définition** de ce ticket : https://github.com/betagouv/rdv-insertion/issues/1444

"Usagers ayant pris RDV dans 2 contextes de RDV différents et / ou étant présents dans 2 organisations différentes : 6813"

**Période : octobre 2023 à fin mars 2024**

J'ajoute ici le [code de Quentin](https://mattermost.incubateur.net/betagouv/pl/x736d44iajdoxp3dqhdn4d1bmy) : 
users_with_two_rdvs = User.joins(:participations).distinct.select do |user|
  user.participations.count >= 2 && user.participations.pluck(:rdv_context_id).uniq.count >= 2
end
users_in_two_organisations = User.joins(:organisations).distinct.select do |user|
  user.organisations.count >= 2
end
users_in_two_organisations_with_rdvs = User.joins(:participations).distinct.select do |user|
  user.participations.count >= 2 && user.participations.map(&:organisation).uniq.count >= 2
end

**Comment by Michaelvilleneuve** [comment]
13951 usagers ont au moins 2 orgas : 
```sql
SELECT COUNT(user_id) AS users_with_at_least_2_organisations
FROM (
    SELECT user_id
    FROM rdvi.users_organisations
    GROUP BY user_id
    HAVING COUNT(DISTINCT organisation_id) >= 2
) AS users_with_2_orgs_or_more;
```

10796 usagers ont pris RDV dans 2 contextes différents / 
```sql
SELECT COUNT(*) AS users_with_at_least_2_rdv_context
FROM (
    SELECT rdvi.participations.user_id
    FROM rdvi.rdv_contexts
    INNER JOIN rdvi.participations ON rdvi.participations.rdv_context_id = rdvi.rdv_contexts.id
    WHERE rdvi.participations.status IN (0, 2, 3, 5)
    GROUP BY rdvi.participations.user_id
    HAVING COUNT(DISTINCT rdvi.rdv_contexts.id) >= 2
) AS users_with_at_least_2;
```


7763 usagers combine les 2 (sont dans 2 orgas et ont pris >=2 rdvs dans 2 contextes différents) : 
```sql
SELECT COUNT(*) AS users_matching_both_conditions
FROM (
    SELECT user_id
    FROM rdvi.users_organisations
    GROUP BY user_id
    HAVING COUNT(DISTINCT organisation_id) >= 2
) AS users_with_at_least_2_orgs_or_more
INNER JOIN (
    SELECT rdvi.participations.user_id
    FROM rdvi.rdv_contexts
    INNER JOIN rdvi.participations ON rdvi.participations.rdv_context_id = rdvi.rdv_contexts.id
    WHERE rdvi.participations.status IN (0, 2, 3, 5)
    GROUP BY rdvi.participations.user_id
    HAVING COUNT(DISTINCT rdvi.rdv_contexts.id) >= 2
) AS users_with_at_least_2_rdv_context ON users_with_at_least_2_orgs_or_more.user_id = users_with_at_least_2_rdv_context.user_id;
```
