### ISSUE TITLE
[FRONT Bug ?] - La typo Marianne ne s'afficherait pas sur RDVI ?

### ISSUE THREAD

**Issue by samanthaauffret** [betagouv/rdv-insertion#1919]
**Comportement observé**

La typo qui s'affiche n'est pas la typo Marianne sur mon navigateur

**Comportement souhaité**

Vérifier si la typo Marianne est bien prise en compte sur RDVI

**Comment by qblanc** [comment]
J'ai testé sous Chrome, Firefox et Safari et chez moi la police s'affiche bien à chaque fois. Je me permets de fermer ce ticket, on pourra faire un test ensemble sur ton ordi @samanthaauffret pour vérifier.

**Comment by samanthaauffret** [comment]
@qblanc , voilà la capture de mes inspecteurs chrome et firefox sur la typo : La typo Marianne est indiqué nulle part

Chrome : system font
![Capture d’écran 2024-04-30 à 14 28 18](https://github.com/betagouv/rdv-insertion/assets/156072816/1b9502a4-1e61-49f0-8da3-f4e86ba5a4bf)
![Capture d’écran 2024-04-30 à 14 28 31](https://github.com/betagouv/rdv-insertion/assets/156072816/b7c69f84-9b06-4a30-9f4d-ef1cbf5ebe3a)

Firefox : system font
![Capture d’écran 2024-04-30 à 14 34 18](https://github.com/betagouv/rdv-insertion/assets/156072816/8f9f3cb3-0c15-4fca-be33-620280614e7e)

Tu as fait tes tests typos sur la prod ou l'environnement de démo ? car j'ai accès uniquement à la démo de mon côté. C'est peut-être la démo qui n'a pas la typo Marianne... Si non, je ne vois pas pour quelles raisons le bug serait uniquement sur mon ordi ?
