### ISSUE TITLE
[Bug] L'enregistrement d'un code SAFIR ne fonctionne pas

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#1930]
Dans la partie "Configuration", je cherche à rentrer un code SAFIR (91008).
En production, Essonne, Agence France Travail de Brétigny-sur-Orge
**Comportement observé**

J'ai aucune erreur et je peux cliquer sur "Enregistrer". Cependant, rien ne se passe et il reste le "-" dans le champs Code Safir.

**Comportement souhaité**
Afficher le bon code Safir

**Comment by Holist** [comment]
Fixed ici https://github.com/betagouv/rdv-insertion/pull/1932
