### ISSUE TITLE
[Bug] Certains agents ne se suppriment pas correctement sur RDV-I

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#1986]
Certains agents supprimés sur rdvsp ne le sont pas sur rdv-i et crée des erreurs au moment de la re-création https://sentry.incubateur.net/organizations/betagouv/issues/81684/?project=16&query=is%3Aunresolved&referrer=issue-stream

**Comment by Holist** [comment]
Me prévenir quand ca recommence.
