### ISSUE TITLE
[TAGS] Remplacer tags du Var (raisons RGPD)

### ISSUE THREAD

**Issue by Evajuliab** [betagouv/rdv-insertion#2132]
Il faudrait modifier les tags du Var pointés pour raisons RGPD

'Incarcéré' à remplacer par 'Absent du foyer' sur les orgas suivantes : 

- CAF DU VAR BRIGNOLES
- CAF DU VAR DRAGUIGNAN 
- CAF DU VAR FREJUS
- CAF DU VAR LA GARDE
- CAF DU VAR LA SEYNE ST MANDRIER
- CAF DU VAR TOULON LA RODE

'Hospitalisation' à remplacer par "Raison médicale" sur les orgas suivantes : 

- CAF DU VAR BRIGNOLES
- CAF DU VAR TOULON LA RODE

**Comment by Holist** [comment]
C'est fait. On a un tag marqué "Raisons judiciaires" pour info (sur la plateforme tél d'orientation de la Meuse). Je ne sais pas ce que ca vaut en terme de RGPD.
