### ISSUE TITLE
Doubler le message d’annulation par un SMS (aujourd’hui on a que le mail)

### ISSUE THREAD

**Issue by qblanc** [betagouv/rdv-insertion#28]
# Description fonctionnelle

- En tant que bénéficiaire RSA
- Je veux recevoir un SMS lorsque j'annule mon rendez-vous
- Afin d'être certain que la manipulation a été effectuée avec succès

# Règles métiers associés

! Mail d'annulation géré par RDV-Solidarités ! 
1) Pour quelle raison pas de SMS pour doublonner ?
2) Possibilité d'ajouter cette feature sur RDV-Solidarités ? (avec un paramétrage mail/sms/mail+sms par organisation/motif ?)
3) Si non, quelle solution adopter ?

# Tests d'acceptance

- L'annulation d'un rendez-vous doit entraîner l'envoi d'un mail ET d'un SMS d'annulation

# Effort : A déterminer
# Valeur : Faible

**Comment by aminedhobb** [comment]
Quand c'est un agent qui l'annule on reçoit un sms.
