### ISSUE TITLE
[Bug] Prendre en charge correctement les fichiers .ods

### ISSUE THREAD

**Issue by qblanc** [betagouv/rdv-insertion#364]
**Comportement observé**
Pour le PIE de Pantin, le chargement du fichier d'upload au format .ods (ou converti au format .xls) ne fonctionnait pas correctement : les colonnes de texte étaient remontées, mais les valeurs des colonnes de chiffres/dates n'étaient pas parsées correctement.

**Comportement souhaité**
Que les fichiers de Pantin puissent être uploadées correctement.

**Comment by qblanc** [comment]
[Modele Orientés Mars ville PANTIN.xls](https://github.com/betagouv/rdv-insertion/files/8603414/Modele.Orientes.Mars.ville.PANTIN.xls)

**Comment by qblanc** [comment]
Le PIE ne fait aucun retraitement sur ce fichier ? Ils pourraient l'uploader tel quel, sans l'avoir ouvert ni modifié ?

**Comment by ClaireCasu** [comment]
Je crois me souvenir que c'était un des sujets de discussion: potentiellement, il faut que le PIE retravaille l'adresse (si c'est chez monsieur/madame). C'est la seule chose à modifier potentiellement

**Comment by ClaireCasu** [comment]
cc @rprebot

**Comment by ClaireCasu** [comment]
La version du PIE est envoyée par Claire aujourd'hui 15:37
