### ISSUE TITLE
Migrer de Webpacker à js-bundling-rails

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#365]
Webpacker est déprécié sur Rails 7 (https://github.com/rails/webpacker#webpacker-has-been-retired-), il faut l'enlever le remplacer par `js-bundling-rails`: https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md

**Comment by qblanc** [comment]
Est-ce que quitte à abandonner Webpack, on ne migrerait pas directement vers les `import maps` ? Tu penses que le jump serait trop/plus compliqué que vers `js-bundling-rails ` ?

**Comment by qblanc** [comment]
@aminedhobb je ne sais pas si tu as vu ma question, je te tag dans le doute :)

**Comment by aminedhobb** [comment]
> Est-ce que quitte à abandonner Webpack, on ne migrerait pas directement vers les `import maps` ? Tu penses que le jump serait trop/plus compliqué que vers `js-bundling-rails ` ?

Je pense que oui surtout tant qu'on utilise react malheureusement 😬
