### ISSUE TITLE
[Bug] Affichage des dates d'invitations sur la page index

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#407]
**Comportement observé**

Parfois la date de dernière invitation n'apparait pas si elle est égale à la date de la première invitation, mais souvent elle apparait quand même:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/7602809/169843027-cea5a81a-c264-40be-b736-bc3c08d269d0.png">

**Comportement souhaité**

Il faudrait un affichage logique: soit on ne montre jamais la date de dernière invitation lorsque celle-ci est égale à la première date, soit on montre toujours la date de dernière invitation

**Comment by qblanc** [comment]
L'affichage est logique : la date de dernière invitation est affichée si il y a *plusieurs* invitations ; sinon, seul la première invitation est affichée (puisqu'il n'y en a pas d'autre). Mais ok pour modifier si tu penses que c'est mieux comme ça.
