### ISSUE TITLE
[Docs] Ecrire dans le wiki la procédure (tech) d'embarquement d'un département/organisations

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#574]
Il faudrait écrire un guide clair qui résume la procédure de configuration d'un nouveau département/organisations sur RDVI/RDVS. 
Il faut y ajouter une checklist à laquelle on peut se référer pour vérifier que tout est bien mis en place.

**Comment by qblanc** [comment]
@aminedhobb j'ai créé la page [ici](https://github.com/betagouv/rdv-insertion/wiki/Configuration-d'un-nouveau-d%C3%A9partement-organisation-sur-RDV-I-RDV-S), est-ce que ça te paraît ok ?
