### ISSUE TITLE
[EPIC stat] Opt out certains départements et/ou organisations du calcul de stats

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#581]
Jusqu'à présent on ne prenait pas en compte les départements qui faisaient de la convocation dans le calcul de stats (=Yonne).
Maintenant que l'on va convoquer des bénéficiaires, il faut changer cette stratégie. 
On peut soit ajouter un autre flag en db au niveau du département ou alors ce serait peut-être une bonne occasion d'introduire un [feature flipper](https://github.com/jnunemaker/flipper).

**Comment by ClaireCasu** [comment]
Supprimer cette EPIC?

**Comment by ClaireCasu** [comment]
Supprimer l'Aude et L'Yonne
