### ISSUE TITLE
[Convocation]: Mettre le nom des rdvs collectifs et des motifs dans les messages de convocation

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#649]

**Comment by Holist** [comment]
Après concertation avec les MDS et CNFS (Yannick et Nesserine) on va partir dans un premier temps sur la solution suivante qui permettra de couvrir en partie le besoin de rdv-insertion : Mettre en place une option au niveau du motif pour ajouter dans les SMS l'intitulé (nom) du rdv pour les rdv collectifs.
Dans le même temps on explore les options qui s'offrent à nous en terme d'ouverture du paramêtrage et de personnalisation des sms (demandes récurrentes des différentes verticales du projet, rdv-insertion, cnfs) tout en restant conforme niveau rgpd/hds.

**Comment by Holist** [comment]
Fait ici : https://github.com/betagouv/rdv-solidarites.fr/pull/3196
