### ISSUE TITLE
[Paramétrage CD 26] Changer les signatures des Mails et des courriers

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#673]
Avant : Fabienne Bouchet, responsable de la Plateforme Mutualisée d'orientation
Après: Fabienne Bouchet, responsable du Pôle Parcours

**Comment by ClaireCasu** [comment]
Nous confirmer quel est l'expéditeur du SMS?

**Comment by aminedhobb** [comment]
> Nous confirmer quel est l'expéditeur du SMS?

Oui je confirme. C'est fait pour le changement de config 👍
