### ISSUE TITLE
[Paramétrage CD31] Création d'une plateforme pour la Haute Garonne

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#698]
**Peux-tu créer l'espace sur RDV-I et RDV-S aussi stp ?**

**Fichier entrée**

Modèle classique :
[Fichier.nouveaux.entrants.xlsx](https://github.com/betagouv/rdv-insertion/files/10237704/Fichier.nouveaux.entrants.xlsx)

**Contextes**

1 contexte pour l'instant : rendez-vous d'orientation

**Délais**

10 jours avant expiration du lien d'invitation

**Courrier**

En-tête : Conseil départemental de la Haute-Garonne
Signature : Direction de la Coordination et du Développement Social
![CD31-logo-horizontal](https://user-images.githubusercontent.com/118368758/207884333-7c418356-ab9f-4530-9956-a9ae2802f806.png)

**Comment by SalmaBennani** [comment]
Hello

**Comment by Holist** [comment]
C'est fait :)
