### ISSUE TITLE
[Paramétrage CD971] Sur la prod

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#699]
Pour la réunion du 21/12
**Fichier entrée**
quel modèle de fichier nouvel entrant en entrée ? 
[Fichier entrée Guadeloupe.xlsx](https://github.com/betagouv/rdv-insertion/files/10239268/Fichier.entree.Guadeloupe.xlsx)

**Contextes**
Contexte RSA Accompagnement

**Délais**
10 jours

**Courrier**
Signature : 
Catherine ROMUALD, Directrice Générale Adjointe de l'Insertion
Logo: 
![image](https://user-images.githubusercontent.com/77394947/207924056-62f43be7-de78-406a-934f-ca8e27edec0b.png)

**Organisations RDVS à lier**
- 3524
- 3525
- 3526
- 3527
- 3528

**Comment by Holist** [comment]
C'est fait, il faut juste trouver une solution pour la civilité de l'allocataire qui n'est pas dans le fichier excel
