### ISSUE TITLE
[Paramétrage CD971] Faire le dispatch par orga

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#709]
Comme dans l'Ain, il faudrait dispatcher les bénéficiaires dans les bonnes organisations en fonction de la colonne "Structure" (5 orgas). 
On prend exactement les mêmes noms que dans RDVS.
[CAF 971]
[Cap Emploi 971]
[Conseil départemental Guadeloupe]
[Mission Locale 971]
[Pôle Emploi 971]

**Comment by Holist** [comment]
@aminedhobb j'aimerai bien en savoir plus sur cette demande pour pouvoir donner un coup de main sur ces demandes de paramêtrage.

**Comment by ClaireCasu** [comment]
Ca a été fait (début 2023). Je ferme
