### ISSUE TITLE
[Paramétrage CD 971] Créer un nouveau contexte pour l'expérimentation SPIE Guadeloupe

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#732]
**Contexte SPIE**:

Contexte **avec référent**

***Mail***
Bonjour Prune JAUNE, Vous êtes demandeur d'emploi et à ce titre vous devez vous présenter à un rendez-vous d'accompagnement afin de démarrer un parcours d'accompagnement.

Pour pouvoir choisir la date et l'horaire de votre rendez-vous, vous pouvez accéder au service RDV-Solidarités en cliquant sur le bouton suivant dans les 3 jours:

[Choisir un créneau](https://github.com/betagouv/rdv-insertion/wiki/Texte-des-messages-par-Contexte)

Ce rendez-vous est obligatoire.

En l’absence de réponse de votre part, vous vous exposez a une réduction ou suspension de votre allocation.

En cas de problème technique, contactez le 01 01 01 01 03

Pour l'équipe SPIE de Guadeloupe

(Pas de logo)

***SMS***
Monsieur Patrice Vert, Vous êtes demandeur d'emploi et vous devez vous présenter à un rendez-vous d'accompagnement. Pour choisir la date et l'horaire du RDV, cliquez sur le lien suivant dans les 3 jours : lien. Ce rendez-vous est obligatoire. En l’absence de réponse de votre part, vous vous exposez a une réduction ou suspension de votre allocation. En cas de problème technique, contactez le 010100101.

**Relance**
Monsieur xx,

Demandeur d'emploi, vous avez reçu un premier message il y a 3 jours vous invitant à prendre RDV au créneau de votre choix afin de démarrer un parcours d’accompagnement. Le lien de prise de RDV suivant expire dans (Y-3) jours: Lien

Ce rendez-vous est obligatoire. En l’absence de réponse de votre part, vous vous exposez a une réduction ou suspension de votre allocation. En cas de problème technique, contactez le xx

**Comment by Holist** [comment]
@aminedhobb je veux bien que l'on traite ça ensemble quand tu auras un moment :)
