### ISSUE TITLE
[DEMO 60] Ajout d'un contexte + Modification du nom du territoire

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#738]
https://www.rdv-insertion-demo.fr/organisations/19/applicants?motif_category=rsa_accompagnement

Nous souhaitons utiliser la plateforme de démo de l'Oise comme plateforme de démo générique. Dans ce sens il faudrait :
- Modifier le nom du territoire en l'appelant Démo générique RDV-I
- Rajouter 2 contextes : RSA - Orientation & RSA - Signature de CER

**Comment by Holist** [comment]
C'est fait, le contexte qui existait déjà (accompagnement) utilisait les référents. J'ai fait la même chose pour les nouveaux contextes mais je peux enlever l'option si tu veux. Je peux également ajouter les logo générique beta.gouv comme j'avais fait pour la démo FT.

**Comment by Holist** [comment]
Ok c'est fait.
Logo beta.gouv ajouté. J'ai aussi mis la carte de France avec le département 70 (comme pour la démo FT)
Et j'ai passé le contexte orientation sans référents.
