### ISSUE TITLE
[Paramétrage CD 74] Lier les nouvelles orgas à RDVI pour le déploiement du 74 + faire le dispatch par organisation

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#740]
**Liaison avec RDV-Insertion** : 
Pour le déploiement du 74, il faudrait lier les orgas RDVS numéros : 3530, 3531, 3532, 3533 et 3534 et 3556

Catégorie
RSA - Accompagnement

Attention : **avec Référent**!

Et il ne faut pas changer la première organisation du 74 (MIE Genevois): il faut qu'elle reste sans référent

Le fichier Excel est le même que pour la MIE Genevois mais contient en plus 2 variables: Référent et Structure.

**Dispatch par organisation**
Lors de la création il faudrait dispatcher les usagers par organisation grâce à la variable Structure, présente dans le fichier.
Les valeurs possibles sont parmi : Cluses, Cruseilles, Novel Plaine, Evian, Thonon Est, Thonon Ouest. Si cela est plus facile, on peut lier les noms à deux composantes par un "_" (je lui communiquerai).

**Comment by ClaireCasu** [comment]
Ce ticket est en lien avec celui ci : https://github.com/betagouv/rdv-insertion/issues/728

En effet, pour les 6 orgas du dessus, il faut inviter sur un rdv référent quand il y a une adresse mail dans la colonne référent, et sinon inviter sur un motif normal.

**Comment by qblanc** [comment]
C'est fait ; n'ayant pas de précision sur ce sujet 'ai gardé la configuration du courrier de la MIE Genevois, mais j'imagine qu'il faudra la modifier, tu me diras ce qu'ils veulent mettre.
