### ISSUE TITLE
[Tech] Ajouter des tests d'intégrations sur la page upload

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#758]
Maintenant que l'on a introduit des tests d'intégrations dans #743 , il est important de tester la partie upload de fichier.
La partie react de l'application n'est pas testé, du coup aujourd'hui on peut facilement introduire des bugs sur cette partie sans s'en rendre compte.
Ajouter ces tests permettra d'éviter ça.

**Comment by Holist** [comment]
Je suis chaud pour m'en occuper quand j'aurai terminé mes issue en cours.

**Comment by aminedhobb** [comment]
Trop bien 👍 .
Les principales choses à tester : 
* Qu'on puisse créer / inviter un bénéficiaire 
* Que le bénéficiaire soit marqué comme déjà créé / invité si c'est le cas 
* Si on est au niveau d'une orga et que le bénéficiaire n'est pas créé sur cette orga, qu'on puisse l'ajouter à l'orga
* Si on est dans un contexte sur lequel le bénéficiaire n'a pas été invité, qu'on puisse l'inviter
* Si on est au niveau du département et qu'on est dans un contexte non géré par le bénéficiaire, qu'on ne puisse pas inviter avec un message "L'allocataire n'appartient pas à une organisation qui gère ce type de rdv"
* Si le bénéficiaire n'est pas créé et qu'on upload la fiche de contacts, que les données soient mises à jours automatiquement
* Si le bénéficiaire est créé et qu'on upload la fiche de contacts, qu'on puisse choisir quelles attributs mettre à jour ou tous les mettre à jour d'un coup
* Si des doublons sont présents dans le fichier les afficher de manière visible
