### ISSUE TITLE
[Paramétrage CD 64] Lier les nouvelles organisations RDVS à RDV-I

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#784]
Pour le 64, il faudrait lier les nouvelles organisations RDVS suivantes à RDVI : 
SDSEI Adour BAB - site d'Anglet
SDSEI Adour BAB - site de Bayonne
SDSEI Adour BAB - site de Biarritz

Contexte Orientation et Fichier habituel du 64.

**Comment by Holist** [comment]
Logiquement c'est bon si tu peux tester au cas ou :)
