### ISSUE TITLE
[Interface de paramétrisation] Restructurer les tables de configuration

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#809]
**User story**
En tant que ..., je veux ... afin que ...

**Description technique**

**Test d'acceptance**

**Comment by qblanc** [comment]
Pour une configuration des contextes plus cohérente, une refonte de la structure des tables de configuration est nécessaire : 
- la table configuration n'est plus porteuse que de : `rdv_with_referents`, `invitation_formats`, `convene_applicant`, `number_of_days_to_accept_invitation`, `number_of_days_before_action_required`
- création d'une table `motif_categories` (traité par @aminedhobb dans la PR #799) ; une configuration peut avoir un seul `MotifCategory`, un `MotifCategory` peut être lié à plusieurs configurations
- création d'une table dédiée aux fichiers d'entrée ; un fichier d'entrée a un `sheet_name` et un `column_names` ; il est lié à un seul département, et peut être lié à plusieurs configurations ; une configuration peut avoir un seul fichier d'entrée
- pas de changement par rapport à la table `messages_configurations`
