### ISSUE TITLE
[Interface de paramétrisation] Faire le front pour l'interface d'admin

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#810]
**User story**
En tant que ..., je veux ... afin que ...

**Description technique**

**Test d'acceptance**

**Comment by qblanc** [comment]
[Cf les captures d'écran et le lien vers Figma sur l'EPIC ](https://github.com/betagouv/rdv-insertion/issues/435#issuecomment-1418849480)
