### ISSUE TITLE
[Interface de paramétrisation] Synchronisation automatique des organisations entre RDV-I et RDV-S

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#811]
**User story**
En tant que ..., je veux ... afin que ...

**Description technique**

**Test d'acceptance**

**Comment by qblanc** [comment]
**User story**
En tant qu'agent ayant accès au paramétrage d'une organisation, je veux que toutes les modifications des infos relatives à mon organisation faites sur rdv-insertion (nom, téléphone, mail) soit répliquée automatiquement sur rdv-solidarités

Description technique
la synchronisation par API pour les organisations se fait déjà dans le sens rdv-s => rdv-i ; elle doit également se faire dans l'autre sens
