### ISSUE TITLE
[Paramétrage 01] Orgas d’Oyonnax et de Nantua

### ISSUE THREAD

**Issue by SalmaBennani** [betagouv/rdv-insertion#818]
**Fichier entrée**
Voici le fichier qu'ils ont : [Squelette Fichier entrée Alfa3a.xlsx](https://github.com/betagouv/rdv-insertion/files/10684314/Squelette.Fichier.entree.Alfa3a.xlsx)

**Contextes**
RSA - Orientation 

Délais
6 jours avant le délai d'expiration du lien.

Pour le CDS d’Oyonnax :

Oyonnax
Dortan
Belleydoux
Echallon
Samognat
Geovreisset
Bellignat
Martignat
Apremont
 

Pour le CDS de Nantua :

Matafelon-Granges
Sonthonnax-la-Montagne
Bolozon
Leyssard
Ceignes
Peyriat
Nurieux-Volognat
Béard-Geovraissiat
Izernore
Montreal-la-Cluse
Brion
Port
Saint-Martin-du-Fresne
Maillat
Chevillard
Condamine
Vieu d’Izenave
Outriaz
Lantenay
Izenave
Corlier
Aranc
Evosges
Prémilieu
Plateau d’Hauteville
Champdor-Corcelles
Brénod
Nantua
Les Neyrolles
Le Poizat – Lalleyriat
Charix
 

Courrier
En entête : ALFA3A pour le Conseil Départemental de l’Ain – 20, rue Castellion 01100 OYONNAX
En signature : La Plateforme RSA ALFA3A – 04.74.73.49.35

Logo : [LOGOS.docx](https://github.com/betagouv/rdv-insertion/files/10581084/LOGOS.docx)

**Comment by Holist** [comment]
C'est good :)

**Comment by Holist** [comment]
C'est fait :)
J'ai ajouté la colonne CDS dans la config du fichier et les bénéficiaires seront automatiquement dispatcher en fonction du code.
