### ISSUE TITLE
[Paramétrage CD 64] Paramétrage du courrier des nouvelles organisations du CD64

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#823]
Pour les 3 nouvelles organisations du 64 (Adour BAB):
Les courriers sont les mêmes que les autres organisations du 64 avec une signature différente : 

"Pour le Président du Conseil départemental et par délégation,"
(sans nom)

**Comment by qblanc** [comment]
Pour la deuxième ligne des en-têtes, il y avait `SERVICE DÉPARTEMENTAL DES SOLIDARITÉS ET DE L’INSERTION - PAU AGGLO` ou `SERVICE DÉPARTEMENTAL DES SOLIDARITÉS ET DE L’INSERTION - PAYS DES GAVES`.
J'ai mis la première option, mais si c'était une nouvelle valeur qu'il aurait fallu mettre, je peux changer

**Comment by ClaireCasu** [comment]
Cela a été fait en février, je ferme.
