### ISSUE TITLE
[Paramétrage CD 23] Créer l'environnement de prod de la Creuse 23 (pour FT)

### ISSUE THREAD

**Issue by ClaireCasu** [betagouv/rdv-insertion#850]
En premier lieu, il faut créer l'organisation RDV-Solidarités.

**Fichier entrée**
Fichier habituel

**Contextes**
Orientation + convocation

**Délais**
quel délai avant expiration du lien d'invitation  ? 

**Courrier**
Jean AUTIER

Directeur
Direction Insertion et Logement
Pôle Cohésion Sociale

![image](https://user-images.githubusercontent.com/77394947/220595053-ef48269b-f2ab-4969-bdce-19571e027bfb.png)

**Comment by qblanc** [comment]
J'ai mis un fichier, celui de la Drôme je pense, pas sûr que ce soit le bon ; on pourra modifier si nécessaire.
Pour le reste c'est configuré, tu me diras si tu veux que je fasse le reste de la config quand vous saurez.
