### ISSUE TITLE
Gérer les agents supprimés sur RDV-S 

### ISSUE THREAD

**Issue by aminedhobb** [betagouv/rdv-insertion#908]
Les agents supprimés sur RDV-S ne sont pas automatiquement supprimés sur RDV-I ce qui peut créer des erreurs : 
https://sentry.incubateur.net/organizations/betagouv/issues/7862/?project=16&query=is%3Aunresolved

**Comment by Holist** [comment]
il n'y a pas d'appel à la methode `generate_payload_and_send_webhook_for_destroy` lors du soft delete de l'agent (idem pour les user/applicants d'ailleurs) coté rdv-s

- Le soucis c'est que coté rdv-s on enlève les orgas avant le soft delete. Il faudrait garder en mémoire l'orgas avec webhook pour pouvoir envoyer le webhook une fois l'agent réellement soft deleted.
- ou alors quand il n'y a plus d'agentrole de notre coté on supprime l'agent. (peut être la solution la plus rapide)
- Je peux (re)questionner l'utilité du soft delete coté rdv-s, c'est quelque chose que l'on a pas encore vraiment tranché. (mais ça pourrait prendre du temps d'investiguer la dessus)

**Comment by Holist** [comment]
On va mettre en place la seconde possibilité. Quand il n'y a plus d'agentrole chez nous on supprime l'agent

**Comment by Holist** [comment]
Close here : https://github.com/betagouv/rdv-insertion/pull/951
