### ISSUE TITLE
[Bug] Permettre d'inviter sans référent au niveau département pour le MIE Genevois

### ISSUE THREAD

**Issue by qblanc** [betagouv/rdv-insertion#992]
**Comportement observé**
Lorsque l'on upload une liste au niveau "Toutes les organisations" dans le 74 et que l'on crée les bénéficiaires, ils sont bien répartis dans les différentes organisations. Toutes ces organisations ont une config `RSA Accompagnement`, et toutes sont des configurations de suivi avec référent, sauf une, celle du MIE Genevois. Pourtant, sur la page `upload` comme sur la page `show`, impossible d'inviter les bénéficiaires assignés à l'association du MIE Genevois sans leur assigner un référent.

**Comportement souhaité**
Pouvoir inviter ces bénéficiaires au niveau "Toutes les organisations" sans leur assigner de référent.

**Source du problème**
Le bug vient de ces lignes dans le `invitations_controller`
```
  def set_organisations
    @organisations =
      policy_scope(Organisation)
      .includes(:motif_categories, :department, :messages_configuration)
      .where(department_level? ? { department_id: params[:department_id] } : { id: params[:organisation_id] })
  end

  def set_preselected_organisations
    @preselected_organisations =
      if @current_configuration.invite_to_applicant_organisations_only?
        @organisations & @applicant.organisations
      else
        @organisations
      end
  end

  def set_current_configuration
    @current_configuration = @organisations.preload(:configurations)
                                           .flat_map(&:configurations).find { |c| c.motif_category == @motif_category }
  end

```
1) `set_organisations` met systématiquement toutes les organisations du département dans `@organisations` lorsque l'on se trouve au niveau de "Toutes les organisations"
2) les invitations ne sont limitées aux organisations dans `set_preselected_organisations` UNIQUEMENT si le département a une configuration unique (ou toujours identique) pour une configuration de motif donnée (ce qui n'est pas le cas du 74)

**Solution envisagée**
La `@current_configuration` devrait être déterminée à partir de `@organisations & @applicant.organisations` plutôt que `@organisations`

**Comment by aminedhobb** [comment]
> La @current_configuration devrait être déterminée à partir de @organisations & @applicant.organisations plutôt que @organisations

Oui bien vu c'est vrai que ça devrait être ça.
En vrai on devrait toujours inviter que dans les orgas du bénéficiaire (et ça enlèverait cette distinction `@organisations` et `@preselected_organisations`) mais je crois que ça embête juste le 64.  Il me semble d'ailleurs que @rprebot et @ClaireCasu avaient prévu de vérifier si on ne voulait pas toujours inviter que dans les orgas du bénéficiaire (auquel cas on peut carrément enlever ce paramètre de la config), mais je pense qu'il y a donc le 64 que ça embêterait.

**Comment by qblanc** [comment]
Yes je suis d'accord avec toi ; en attendant de voir si on peut faire ce que tu dis, j'ai fait une PR pour fix le problème.
